// console.log("Welcome to tut13");
// let today = new Date();
// // console.log(today);
// let otherDate = new Date("08/15/1947");
// console.log(otherDate);
// let a;
// a = otherDate.getDay();
// a = otherDate.getDate();
// a = otherDate.getMinutes();
// a = otherDate.getHours();
// a = otherDate.getSeconds();
// a = otherDate.getMonth();
// console.log(a);
// otherDate.setDate(23);
// // console.log(otherDate);
// otherDate.setMonth(02);
// // console.log(otherDate);
// otherDate.setFullYear(1900);
// otherDate.setMinutes(15);
// otherDate.setHours(5);
// otherDate.setSeconds(58);
// console.log(otherDate);
console.log(__dirname);
