console.log("Welcome to tut5");
let myVar;
myVar = String(56);
console.log(myVar, typeof myVar);
let booleanVar = String(true);
console.log(booleanVar, typeof booleanVar);
let date = String(new Date());
console.log(date, typeof date);
let arr = String([1, 2, 45, 65]);
console.log(arr.length, typeof arr);
let i = 9;
console.log(i.toString());
let ari = Number("6565");
console.log(ari, typeof ari);
let number = Number("59.2558563");
console.log(number.toFixed(25), typeof number);
let myStr = "568";
let myNum = 25;
console.log(myStr + myNum);
